language: python
sudo: false

env:
  - LUA="lua 5.1"
  - LUA="lua 5.2"
  - LUA="lua 5.3"
  - LUA="luajit 2.0"
  - LUA="luajit 2.1"

before_install:
  - pip install hererocks
  - hererocks env --$LUA -rlatest
  - source env/bin/activate
  - luarocks install ldoc
  - luarocks install luaunit
  - luarocks install luacov
  - luarocks install luacov-coveralls

script:
  - ./tests/run_examples.sh
  - ldoc --output contents --dir docs .
  - lua -lluacov tests/run.lua

after_success:
  - luacov-coveralls
