project = 'forma'
title = 'forma Reference Manual'
description = 'A grid shape generation package'
format = 'markdown' 
readme = 'README.md'
examples = 'examples'

file = {
        './forma/point.lua',
        './forma/pattern.lua',
        './forma/primitives.lua',
        './forma/subpattern.lua',
        './forma/automata.lua',
        './forma/neighbourhood.lua',
        './forma/util.lua'
    }
