name: Documentation
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  generate_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: leafo/gh-actions-lua@v11
      - uses: leafo/gh-actions-luarocks@v5
      - name: Install ldoc
        run: luarocks install ldoc
      - name: Generate documentation
        run: ldoc --output contents --style=./ --dir docs .
      - name: Upload pages artifact
        if: ${{ github.event_name == 'push' }}
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

  deploy_docs:
    if: ${{ github.event_name == 'push' }}
    needs: generate_docs
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
